dist: xenial
language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      name: "Lint"
      env: LINT="true"

    - python: "3.5"
      name: "3.5 Xenial"
    - python: "3.6"
      name: "3.6 Xenial"
    - python: "3.7"
      name: "3.7 Xenial"
    - python: "3.8"
      name: "3.8 Xenial"

install: pip install -U tox-travis

script:
- |
  if [ "$LINT" == "true" ]; then
    tox -e lint
  else
    tox
  fi

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: pmrowla
  password:
    secure: "SYji4EYgd8xy9kTuLd8LDWdN2hH4bF7wspJGYQGbmYT/Ly1SdETH9zfFg8OXFLtCxYReZLn2hd+pp321zkrnguZXAqB1mR908mVeUeFwlnAwZiHWN1zWdoC83IGWImNci6U5CX0To7pyMLOvXEb0DZgJn1/keS2aI+IIXRCxYwX2h4WCOeeD6C45VVYg0oE15Xmv8epuFDuJOViPDlkU9HEx6GVlrPJCo2gL9HVpAQYSVJSZ7ClHGSRPquQwLgeE0iyf6KpFJOdvoOcwtbTwk+T8a+6GsRfAVp2lgGodcnq3nmNAm0MZ8dLKQcyz1GUa33ljipcCPI9KQv9ddZX+uVXqEM0GSIMKLzFX3x1IxzjXgSke3CgFFk00vNwFnwnrmoW9QQanRilmIQwS4jxmsZaYvTv5NuCyD4TG1ewb2+a36E4rKp49dUYAoaHBMCHUun2D7AUolOUphWVyCM9KWQ0nX/I/ZGRLwMfz3+rHGsVaiIr9EAz8KblLC3KhEuKMocxozYSiUPrGYl5Jq4eU1c8xLHzqftSmOq/sg9eOqjUyInkCELx1Pwi2HMrpU6wbhN4GbhR90B/Fk/Q2p9I+zxhMxyp3FHXeaYNgiz8unMW4GzqEttu8NBheEiY/ycIMcD1MrokwMEDRirRypmx3e+x/0uCD66PPK+5D1B1vydU="
  on:
    tags: true
    repo: pmrowla/pylivemaker
    python: 3.6
