dist: xenial
language: python
cache:
  pip: true
  directories:
  - "$HOME/.cache/pre-commit"

matrix:
  fast_finish: true
  include:
  - python: '3.6'
    name: Lint
    env: LINT="true"
  - python: '3.5'
    name: 3.5 Xenial
  - python: '3.6'
    name: 3.6 Xenial
  - python: '3.7'
    name: 3.7 Xenial
  - python: '3.8'
    name: 3.8 Xenial

install: pip install -U tox-travis

script:
- |
  if [ "$LINT" == "true" ]; then
    tox -e lint
  else
    tox
  fi

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: Mu0qitljjKJV6YorTOTnf1fIxDr5EQWejEvaT9/a5pGZnYsW3L9P8IuCEp/TobvtbN2XSBHG32+TLlrlvpmJHpJb4Q5JhjjVqQHYXfPgpGEAmVajCX1sQEkhEkvZJ+xwl9pjOAbhNiGD1CiTDaS5VDSYZfxsEzUMLcxRvsNUndvqp3XYcNHsW56bs+/xSu8hT5CfdGdpzcjEGFNdp1icBj+vZd8nrpNE8cSDh8r6Vhxhqr91ye0TbBV0epENtTq85NwM+fXukQpgpJd17WNxI6RJJsZzilsAc0lcQALGKYNZpHwgGXmOU0ZcrAQuemv+NbkAObuT1Szv/r8/V5GA9pZVc7DJ+RCEkqSV9zR5KfL+J3qauK1NJr0L5/RG7MM/vLkj3d8eXYw4oWP6lVgews858nLYo0BXfDTieY+g+C62hxSfrj0OZnbJdLkdHO4EMfQXPPZjTSCNbnEEIv60I/W/BB9SBL5DWmEXAURpNym7fQzVCiWihheprzk1pSnwzViIDW7Vd8uZ3WoRSQK9iyxkp+UIXPnVwKdGWelHk24oQnS7AvwSgw0zfnVRuyUgNSzg6K9FX+vLQuwGz5Lt/8ZG7B3/J804Vqc6uuHQIb2LgHDhx9qSjG8tc4XlZAsVR10Y1/3PkxGSQjROK1Cu/eKUyJe25TH35Ncar1Bgo0w=
  on:
    tags: true
    repo: pmrowla/pylivemaker
    python: 3.6
